server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
spring:
  application:
    name: presence-service
  data:
    couchbase:
      connection-string: ${CB_DB_URL}
      username: ${CB_DB_USERNAME}
      password: ${CB_DB_PASSWORD}
      bucket:
        name: presence_bucket
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.example.presence_service.entity.EventPresence
        spring.json.trusted.packages: com.example.presence_service.entity
service:
  identity:
    url: lb://identity-service/identity/validate
  post:
    url: lb://post-service/posts/search
  notification:
    url: lb://notification-service/notifications
logging:
  level:
    root: INFO
    com.example.presence_service: DEBUG
