server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
spring:
  application:
    name: trending-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    cors:
      allowed:
        origins: '*'
        methods: '*'
        headers: '*'
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.example.trending_service.dto.request.TrendingEventRequest
        spring.json.trusted.packages: com.example.trending_service.dto.request
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0
service:
  identity:
    url: lb://identity-service/identity/validate
  post:
    url: lb://post-service/posts
  notification:
    url: lb://notification-service/notifications
  search:
    url: lb://search-service/search
logging:
  level:
    root: INFO
    com.example.trending_service: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info