server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
spring:
  application:
    name: message-service
  data:
    couchbase:
      connection-string: ${CB_DB_URL}
      username: ${CB_DB_USERNAME}
      password: ${CB_DB_PASSWORD}
      bucket:
        name: message_bucket
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: message-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

service:
  identity:
    url: lb://identity-service/identity/validate
  friend:
    url: lb://identity-service/friends
  profile:
    url: lb://identity-service/graphql
logging:
  level:
    root: INFO
    com.example.message_service: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 3600000
  refreshTokenExpiration: 604800000