package com.example.post_service.enums;

public enum PostEventType {
    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,
    POST_PUBLISHED,
    POST_UNPUBLISHED,
    COMMENT_ADDED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    COMMENT_REPLY_ADDED,
    COMMENT_REPLY_UPDATED,
    COMMENT_REPLY_DELETED,
    POST_LIKED,
    POST_UNLIKED,
    LIKE_COMMENT,
    UNLIKE_COMMENT
}
