server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
spring:
  application:
    name: music-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    cors:
      allowed:
        origins: '*'
        methods: '*'
        headers: '*'
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
service:
  identity:
    url: lb://identity-service/identity/validate
logging:
  level:
    root: INFO
    com.example.post_service: DEBUG
spotify:
  client:
    id: ${SPOTIFY_ID}
    secret: ${SPOTIFY_SECRET}
  redirect-uri: ${REDIRECT_URI}
  auth-uri: https://accounts.spotify.com/authorize
  token-uri: https://accounts.spotify.com/api/token
  user-uri: https://api.spotify.com/v1/me
